name: task_tracker_backend
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.6

dependencies:
  args: ^2.3.0
  build_runner: ^2.4.9
  dotenv: ^4.2.0
  mongo_dart: ^0.10.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  json_annotation: ^4.9.0
  bcrypt: ^1.1.3
  dart_jsonwebtoken: ^2.14.0
  shelf_swagger_ui: ^1.0.0+2

dev_dependencies:
  json_serializable: ^6.8.0
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.21.0
